homeAssistant:
    url: "192.168.1.19:8123"
    token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIxOTQ1MzBlMmZiY2U0MjJiODgyNjVkYjc2N2NhYzJjNyIsImlhdCI6MTYyMzgxMjc2OCwiZXhwIjoxOTM5MTcyNzY4fQ.bzKTV01SG1euLtUQ1vRWlCzkyiSKXp1rJhPW82bWPDE"
lutron:
    url: "192.168.1.150"
    port: 23
    file: "lutron_configuration.json"
    username: "lutron"
    password: "integration"
zwave:
    driver_location: "/dev/ttyACM0"
kasa:
  devices: 
    - "192.168.1.151"
    - "192.168.1.156"
    - "192.168.1.161"
life360:
  username: "adam9190@gmail.com"
  password: "CFmp5gjLNG4Q"
  authenticationToken: "cFJFcXVnYWJSZXRyZTRFc3RldGhlcnVmcmVQdW1hbUV4dWNyRUh1YzptM2ZydXBSZXRSZXN3ZXJFQ2hBUHJFOTZxYWtFZHI0Vg=="
myq:
    username: "adam9190@gmail.com"
    password: "Martian9190!"
harmony:
    ip_address: "192.168.1.219"
menu:
  - index: 1
    areaName:  "Family Room"
    hass:
      - "light.family_room_ceiling_fan_light"
      - "light.family_room_cove_lights"
  - index: 2
    areaName:  "Kitchen"
    hass:
      - "light.kitchen_main_lights"
      - "light.kitchen_table_chandelier"
  - index: 3
    areaName:  "Dining Room"
    hass:
      - "light.dining_room_chandelier"
  - index: 4
    areaName:  "Living Room"
    hass:
      - "light.living_room_ceiling_fan_light"
  - index: 5
    areaName:  "Basement"
    hass:
      - "light.basement_stairs_step_lights"
      - "light.basement_stairs_main_lights"
  - index: 6
    areaName:  "Playroom"
    hass:
      - "light.playroom_main_lights_1"
      - "light.playroom_main_lights_2"
    kasa:
      - "192.168.1.156"
  - index: 7
    areaName:  "Master Bedroom"
    hass:
      - "light.master_bedroom_ceiling_fan_light"
    kasa:
      - "192.168.1.161"
  - index: 8
    areaName:  "Kids Bathroom"
    hass:
      - "light.kids_bathroom_main_lights"
  - index: 9
    areaName:  "Office"
    hass:
      - "light.office_sconces"
      - "light.office_main_lights"
    kasa:
      - "192.168.1.151"
  # - index: 10
  #   areaName: "Main"
  #   harmony: 
  #     - activities:
  #         - state: "off"
  #           activity: "-1"
  #         - state: "on"
  #           activity: "40771265"
    # custom:
    #   - type: "lutron"
    #     name: "All Lights"
    #     devices:
    #       - "2"
    #       - "3"
    #       - "4"
    #       - "5"
    #       - "6"
    #       - "7"
    #       - "9"
    #       - "10"
    #       - "11"
    #       - "12"
    #       - "14"
    #       - "16"
    #       - "18"
    #       - "19"